### ISSUE TITLE
Project won't build

### ISSUE THREAD

**Issue by balhoff** [calliem/compute-expect#6]
I updated my Eclipse project from the Maven file, but I still see that `org.apache.commons.math3.stat.regression.OLSMultipleLinearRegression` cannot be resolved. Does an update to `pom.xml` need to be committed?

**Comment by calliem** [comment]
Updated pom.xml, so it should be able to build now. 

Also, the OLSMultipleLinearRegression package that I'm using appears to compute coefficients differently than the statsmodel python package did, so results currently may not match up.

**Comment by calliem** [comment]
Also the scoresGeneTaxonPath string in Main should be changed to "Scores_Sizes.txt" if you're trying to run it with the entire dataset. The current file is a truncated version that I have been using for testing purposes.

**Comment by balhoff** [comment]
Thanks, my build is working now. Does commons-math 3.5 supersede 1.2? If so you may want to remove 1.2 from the dependencies because you may unexpectedly use old versions of classes.
